spring:
  application:
    name: product-importer

api:
  base-url: https://api-business.click-market.ru
  username: "${CLICK_USERNAME}"
  password: "${CLICK_PASSWORD}"

logging:
  level:
    root: INFO
    com.example.productimporter: DEBUG

images:
  directory: input/images
  placeholder: input/images/no-image.png

import:
  mode: PREVIEW # PREVIEW/FULL
  excel-file: input/missing-products/1.xlsx
  hyperlinks-file: input/hyperlinksfile/1.xlsx
  product-name-column: 1

storage:
  downloads-directory: input/temp_images
